openapi: 3.0.3
info: 
  title: Shorten URL Service
  description: |-
    This service offers REST Endpoints to shorten URLs.
  version: 1.0.0
servers:
  - url: http://localhost:3333/api/v1
tags:
  - name: health
    description: Server health check
  - name: url
    description: Short URL management
  - name: account
    description: Account management - login/register
paths:
  /health:
    get:
      tags:
        - health
      summary: server healthcheck endpoint
      responses:
        '200':
         description: Successful operation.
         content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Shorten URL API service is running.
        '429':
          description: Too many requests - Rate limiter
        '500':
          description: Internal Server Error.
  /url-record:
    post:
      tags:
        - url
      summary: create a MiniURL
      description: save a url and return a unique shortUrlId which can be used as MiniURL
      operationId: shortenUrl
      parameters:
        - name: x-correlation-id
          in: header
          description: correlationId for logging and traceability
          required: true
          schema:
              type: string
              example: random-dsljqlksadas-uuid
      requestBody:
        content:
          application/json:
            schema:
              required:
                - url
              type: object
              properties:
                url:
                  type: string
                  example: https://www.google.com
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrlId: 
                    type: string
                    example: jTG0e
        '400':
            description: Validation Error - Invalid URL
        '429':
            description: Too many requests - Rate Limiter
        '500':
            description: Internal Server Error.
    get:
      tags:
        - url
      summary: get original url
      description: Fetch originalUrl based on miniUrl id and update hits count
      operationId: getUrlRecord
      parameters:
        - name: miniUrl
          in: query
          description: MiniUrl id
          required: true
          schema:
            type: string
            example: SjJXl
        - name: x-correlation-id
          in: header
          description: correlationId for logging and traceability
          required: true
          schema:
            type: string
            example: randomasdjlkjaskdj
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/UrlRecordResponse'
        '404':
          description: Not Found.
        '400':
          description: Validation Error
        '429':
            description: Too many requests - Rate Limiter
        '500':
          description: Internal Server Error. 
  /urls:
    get:
      tags:
        - url
      summary: get urls created by user
      operationId: urlsCreatedByUser
      parameters:
        - name: x-correlation-id
          in: header
          description: correlationId for logging and traceability
          required: true
          schema:
              type: string
              example: random-dsljqlksadas-uuid
        - name: Authorization
          in: header
          description: JWT Bearer Auth token generated at login
          required: true
          schema:
              type: string
              example: Bearer fakeToken
      responses:
        '200':
         description: Successful operation.
         content:
            application/json:
              schema:
                type: object
                properties:
                  urls:
                    type: array
                    items:
                      $ref: '#/components/schemas/UrlRecordResponse'

        '429':
          description: Too many requests - Rate limiter
        '500':
          description: Internal Server Error.


  /login:
      post:
        tags:
        - account
        summary: login to shorten url portal
        description: validate password and return jwt accesstoken
        operationId: login
        parameters:
        - name: x-correlation-id
          in: header
          description: correlationId for logging and traceability
          required: true
          schema:
              type: string
              example: random-dsljqlksadas-uuid
        requestBody:
          content:
            application/json:
              schema:
                required:
                  - userName
                  - password
                type: object
                properties:
                  userName:
                    type: string
                    example: fakeUser
                  password:
                    type: string
                    example: fakepass1!A
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    msg: 
                      type: string
                      example: Authentication successful.
                    accessToken:
                      type: string
                      example: fakeTokenasdlkj
                    user:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 65f5eb134f4dbaf667be8f89
                        userName:
                          type: string
                          example: fakeeUser
                        firstName:
                          type: string
                          example: fakeFirst
                        lastName:
                          type: string
                          example: fakeLast
                        email:
                          type: string
                          example: fake@fake.com
                        createdAt:
                          type: string
                          example: "2024-03-16T18:55:15.543Z"
                        updatedAt:
                          type: string
                          example: "2024-03-18T21:43:35.354Z"
                        __v:
                          type: number
                          example: 0
                        lastLoginAt:
                          type: string
                          example: "2024-03-18T21:42:42.198Z"
          '400':
              description: Validation Error 
          '429':
              description: Too many requests - Rate Limiter
          '500':
              description: Internal Server Error.
  /registration:
    post:
      tags:
        - account
      summary: Register for an account
      description: creates a user account for short url management
      operationId: registration
      parameters:
        - name: x-correlation-id
          in: header
          description: correlationId for logging and traceability
          required: true
          schema:
              type: string
              example: random-dsljqlksadas-uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationBody'
      responses:
          '200':
            description: 'Successfull operation.'
            content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message: 
                        type: string
                        example: Account registration successful.
          '400':
                description: Validation Error 
          '429':
                description: Too many requests - Rate Limiter
          '500':
                description: Internal Server Error.



components:
  schemas:
    UrlRecordResponse:
      type: object
      properties:
        UrlRecord:
          type: object
          properties:
            _id:
              type: string
              example: 65ecd5592a04bcd9c6aba9a2
            originalUrl:
              type: string
              example: https://www.google.com
            miniUrl:
              type: string
              example: SjJXl
            hits:
              type: number
              example: 1
            createdAt:
              type: string
              example: '2024-03-09T21:32:09.232Z'
            updatedAt:
              type: string
              example: '2024-03-09T21:49:06.869Z'
            __v:
              type: number
              example: 0
        msg:
          type: string
          example: Found!
    RegistrationBody:
        required:
                - firstName
                - lastName
                - userName
                - password
                - confirmPassword
                - email
        type: object
        properties:
          userName:
            type: string
            example: fakeUser
          firstName:
            type: string
            example: fakeFirst
          lastName:
            type: string
            example: fakeLast
          email:
            type: string
            example: fake@fake.com
          password:
            type: string
            example: fakepass1!A
          confirmPassword:
            type: string
            example: fakepass1!A




